{
    {url="https://raw.githubusercontent.com/HeroBrine1st/RSA/master/RSA/text_support.lua",path="/lib/RSA/text_support.lua"},
    {url="https://raw.githubusercontent.com/HeroBrine1st/RSA/master/RSA/Basic.lua",path="/lib/RSA/RSAB.lua"},
    {url="https://raw.githubusercontent.com/HeroBrine1st/RSA/master/RSA/init.lua",path="/lib/RSA/init.lua"},
    {url="https://raw.githubusercontent.com/HeroBrine1st/RSA/master/metaint.lua",path="/lib/metaint.lua"},
    {url="https://raw.githubusercontent.com/HeroBrine1st/RSA/master/RSA/Math/init.lua",path="/lib/RSA/Math/init.lua"},
    {url="https://raw.githubusercontent.com/HeroBrine1st/RSA/master/RSA/Math/MillerRabinTest.lua",path="/lib/RSA/Math/MillerRabinTest.lua"},
    {url="https://raw.githubusercontent.com/HeroBrine1st/RSA/master/RSA/Math/RandomNum.lua",path="/lib/RSA/Math/RandomNum.lua"}
}